### ISSUE TITLE
Remove `XX` region for subregional nodes

### ISSUE THREAD

**Issue by trevorb1** [Electricity-Transmission-Database/electricity-transmission-database#3]
In the `data/csv/nodes.csv` file, for regions that have subregional representation, there are still `XX` nodes. For example, Canada is displayed as below: 

| Node   | Country | Population | Centroid_Lat | Centroid_Lon | Pop_Lat | Pop_Lon | Node_Verbose      |
|--------|---------|------------|--------------|--------------|---------|---------|-------------------|
| CAN-XX | Canada  | 5429524    | 43.74        | -79.37       | 43.74   | -79.37  |                   |
| CAN-AB | Canada  | 1239220    | 51.05        | -114.07      | 51.05   | -114.07 | Canada - Alberta  |
| CAN-AR | Canada  | 403131     | 44.65        | -63.59       | 44.65   | -63.59  | Canada - Atlantic |
| ...    |         |            |              |              |         |         |                   |

Other examples I believe are Canada, USA, Brazil, China, Australia, and Russia. 

I think the `XX` nodes should be removed for all of these regions?

**Comment by maartenbrinkerink** [comment]
I think so to and the same for the aggregated regions that are used in the modelling for OG/FEO but are no part of the transmission database (e.g. Canada Central). I'll try to align the input files.

**Comment by maartenbrinkerink** [comment]
I've updated the node list accordingly in the latest commit. @amanmajid somewhere there's a '-' being added in the region names (e.g. 'USA-ER' and 'IRL-XX') which can lead to conflicts based on the naming convention in the transmission database and as used in OG ('USAER'). Is it possible to remove this? Will also need to be done in the nodes.csv if it can be removed. Also, is the 'node_code_name_mapping' csv being used somewhere as this still includes regions as used in FEO (e.g. Canada Central). If it's not used I suggest to remove it to prevent confusion.

**Comment by trevorb1** [comment]
@maartenbrinkerink @amanmajid I agree on merging the files! The ones I am seeing are: 
1. `data/csv/nodes.csv`
2. `data/csv/node_code_name_mapping.csv`
3. `database_mappings.csv` (attached here from our slack messages) 

The `database_mappings.csv` holds regions to be merged into one. This would make it easier to coordinate the spatial representation map. Not sure if the subregion names match up perfectly with the other files or not 

[database_mappings.xlsx](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/files/13663853/database_mappings.xlsx)

**Comment by maartenbrinkerink** [comment]
The nodes.csv has the exact same regions as the 'database_mappings' with the only difference that 'nodes.csv' has '-' as delimiter in the region names (which I suggest to change but I'm not sure where the '-' comes from in the script since it's not being read from the 'nodes.csv'). 'node_code_name_mapping' is redundant I think. Merging everything into one spatial mapping file that can be used for all maps makes sense to me (including the 'exclude' map and the 'spatial representation' map).

**Comment by amanmajid** [comment]
@maartenbrinkerink The '-' is being added [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/51fe41e2b42df176d6fca7d146c05bf68ef095c8/src/database.py#L82-L101). I will remove this to keep the three-letter ISO codes only.

@trevorb1 Just to check, are you saying above that I can delete the three `.csv` files and replace them with the excel file you linked above? If so, that sounds like a great idea and I'm happy to refactor the code to do that.

**Comment by trevorb1** [comment]
@amanmajid Can't quite just do a straight replace, but they all have very similar data. I can create what I think should be the master file to replace the csvs today and drop it here for discussion

**Comment by trevorb1** [comment]
@amanmajid @maartenbrinkerink My proposal for a single csv nodes file can be found [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/add-subregions/data/csv/nodes.csv). Please note, it does not address the `-` issue. This file has been integrated into PR #6 already. Please feel free to change accordingly tho! 

I moved the region description column contents to the shapefile creation script [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/add-subregions/src/subregions.py) (see the mappers). My motivation for doing this was we can keep the `nodes.csv` as a csv since special characters was causing formatting issues. Moreover, the names sometimes did not match up perfectly with the names from GADM, so directly reading in the names wasnt feasible. If we did want to export the mappers to a file for reference, that is an easy thing to do :)

**Comment by trevorb1** [comment]
@amanmajid I have added shapefiles for each subregion in PR #6. Each country that has subregions has its own shapefile, as I thought this was more explicit. However, if you prefer all subregions in a single shapefile, that is an easy update. These shapfiles have a `region`, `subregion`, and `geometry` column. `region` is the 3-letter iso while `subregion` is 2-letter code.

After chatting this morning, it seems like you have a good idea on how to create the spatial representation map described in issue #4? If this is correct, maybe I can leave it to you to integrate everything together? If not, please just let me know and I can help! :)

**Comment by trevorb1** [comment]
@maartenbrinkerink when recreating the admin level 1 boundaries to regional mappings, a few questions came up. If you have thoughts on any of them, can you please let me know! All questions come from the comments in the mappers shown [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/add-subregions/src/subregions.py).  

1. For Australia there are three unaccounted for regions; `AshmoreandCartierIslands`, `CoralSeaIslandsTerritory`, and `JervisBayTerritory`. However, these seem to be very small geometry. I am assuming it is okay to drop them. 

![image](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/assets/67297083/4596d5e1-8cbe-45a9-9d58-08016eaf979b)

2. For India, there is a region called `Ladakh` that does not exist in the GADM data. However, there is an unassigned GADM region of `Lakshadweep`. Are these the same? 

3. The Japan mapping seems incorrect? GADM lists about 40 admin level 1 regions, however, the current database mapping file only lists 5 regions? Right now, I have not mapped over Japan because of this. 

4. In Russia, the database mapping file lists `Chita`, `Chukchi Autonomous Okrug`, `Maga Buryatdan`, and `Moskovskaya`, which do not appear in the GADM data. However, the GADM dataset list `Chukot`, `Magadan`, `MoscowCity` and `Zabaykal'ye` which do not appear in the database mappings file. Im pretty sure `MoscowCity` goes with `Moskovskaya`, and `Maga Buryatdan` goes with `Magadan`, but not sure about the others. I am happy to just match the GADM data to whatever the closest region is, but just thought I would check first if you knew. 

Happy to hop on a call to discuss any of this it thats easier as well! :)

**Comment by maartenbrinkerink** [comment]
> @maartenbrinkerink when recreating the admin level 1 boundaries to regional mappings, a few questions came up. If you have thoughts on any of them, can you please let me know! All questions come from the comments in the mappers shown [here](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/add-subregions/src/subregions.py).
> 
> 1. For Australia there are three unaccounted for regions; `AshmoreandCartierIslands`, `CoralSeaIslandsTerritory`, and `JervisBayTerritory`. However, these seem to be very small geometry. I am assuming it is okay to drop them.
> 
> ![image](https://private-user-images.githubusercontent.com/67297083/290738003-4596d5e1-8cbe-45a9-9d58-08016eaf979b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDI1NzcsIm5iZiI6MTcwMjY0MjI3NywicGF0aCI6Ii82NzI5NzA4My8yOTA3MzgwMDMtNDU5NmQ1ZTEtOGNiZS00NWE5LTlkNTgtMDgwMTZlYWY5NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyMTExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MTIzNWRjMGRhMGU0YWQ1NGVhZGVjNzJjNmQyODQzODk4M2NiMTU5YTUyMDhlY2NlZWYzYmUwOGQyNmMzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjvKhSjMUlWYhXWOpno_EG68ccFxyMEKlRbMDC0lu_E)
> 
> 2. For India, there is a region called `Ladakh` that does not exist in the GADM data. However, there is an unassigned GADM region of `Lakshadweep`. Are these the same?
> 3. The Japan mapping seems incorrect? GADM lists about 40 admin level 1 regions, however, the current database mapping file only lists 5 regions? Right now, I have not mapped over Japan because of this.
> 4. In Russia, the database mapping file lists `Chita`, `Chukchi Autonomous Okrug`, `Maga Buryatdan`, and `Moskovskaya`, which do not appear in the GADM data. However, the GADM dataset list `Chukot`, `Magadan`, `MoscowCity` and `Zabaykal'ye` which do not appear in the database mappings file. Im pretty sure `MoscowCity` goes with `Moskovskaya`, and `Maga Buryatdan` goes with `Magadan`, but not sure about the others. I am happy to just match the GADM data to whatever the closest region is, but just thought I would check first if you knew.
> 
> Happy to hop on a call to discuss any of this it thats easier as well! :)

1. Jervis Bay is a peninsula of AUSSW so can be added (but dropped is also fine if easier) and the other two are non-covered islands so you can drop them.
2. Lakshadweep are islands and can be removed. Ladakh is a contested area part of the larger Kashmir area which I think is part of the dataset ('Jammu and Kashmir' in the original dataset)? If Kashmir is in GADM then Ladakh can be dropped.
3. You're right, they were missing in the original mapping file since the Cartopy package I used (for which I created the mapping initially) did not support admin 1 for Japan. I've added the mapping below so you can integrate it where needed.
4. Chukchi and Chukot correspond to the same node (RUSFE), Maga Buryatdan/Magadan are the same and Moskovskaya/MoscowCity as well. Chita is a former oblast that merged with some other smaller regions into 'Zabaykal'ye` so you can swap Chita with that one.

Aichi | JPNCE
Akita | JPNTO
Aomori | JPNTO
Chiba | JPNTO
Ehime | JPNSH
Fukui | JPNCE
Fukuoka | JPNKY
Fukushima | JPNTO
Gifu | JPNCE
Gunma | JPNTO
Hiroshima | JPNCE
Hokkaido | JPNHO
Hyogo | JPNCE
Ibaraki | JPNTO
Ishikawa | JPNCE
Iwate | JPNTO
Kagawa | JPNSH
Kagoshima | JPNKY
Kanagawa | JPNTO
Kochi | JPNSH
Kumamoto | JPNKY
Kyoto | JPNCE
Mie | JPNCE
Miyagi | JPNTO
Miyazaki | JPNKY
Nagano | JPNCE
Nagasaki | JPNKY
Nara | JPNCE
Niigata | JPNTO
Oita | JPNKY
Okayama | JPNCE
Okinawa | JPNOK
Osaka | JPNCE
Saga | JPNKY
Saitama | JPNTO
Shiga | JPNCE
Shimane | JPNCE
Shizuoka | JPNCE
Tochigi | JPNTO
Tokushima | JPNSH
Tokyo | JPNTO
Tottori | JPNCE
Toyama | JPNCE
Wakayama | JPNCE
Yamagata | JPNTO
Yamaguchi | JPNCE
Yamanashi | JPNCE

**Comment by trevorb1** [comment]
Great, thanks @maartenbrinkerink! 
1. I included `JervisBayTerritory` and dropped `AshmoreandCartierIslands` and `CoralSeaIslandsTerritory` 
2. I dropped `Lakshadweep` and ignored missing `Ladakh`, as `JammuandKashmir` is already included
3. The Japan mappings matched perfectly, thanks! 
4. Updated `MoscowCity`, `Magadan`, `Chukot`, and `Zabaykal'ye` following your notes

**Comment by amanmajid** [comment]
I've slightly lost track of what the actual issue is here. 

It seems @trevorb1 has fixed the nodes with subregional representation above (thanks!). 

Also, I've now changed the code so that `-XX` does not appear in any of the interactive plots. However, there are still nodes with `-XX` in their name in `nodes.csv`, which I don't think is much of an issue. In fact, we might need to keep it there as that's the notation used in OSeMOSYS-Global, so should probably keep that notation to keep mapping consistent. 

Given the above, can we go ahead and close this issue?

**Comment by trevorb1** [comment]
@amanmajid ahhh. My fault on changing topics within the same issue ticket. The original issue has been resolved, and spatial map conversation can take place in ticket #4.
