### ISSUE TITLE
Add Spatial Representation Map 

### ISSUE THREAD

**Issue by trevorb1** [Electricity-Transmission-Database/electricity-transmission-database#4]
Add in a spatial representation map similar to shown below. 

![image](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/assets/67297083/8f9a7765-c67c-40b0-8e7c-cdc1b15ffdb0)

**Comment by amanmajid** [comment]
Hi @trevorb1 

Thanks so much for your work on #6 - super helpful.

After some thought, I'm now thinking that it'd be best to keep all spatial data in one shapefile rather than having lots of files (too messy!). I'd suggest we create one shapefile (e.g., `spatial_representation.shp`) that includes boundaries for all countries and subregional boundaries. We can also include a boolean `EXCLUDED` column so that we can get rid of `excluded_regions.shp`. 

Thoughts?

**Comment by trevorb1** [comment]
@amanmajid That makes sense to me! I can update the script to make a single reproducible shape file today. I will include a column  for `EXCLUDED` as well, to match the datastructure of the current shape file being used. 

If I get that done for today, will that leave you enough time to make the spatial representation map before holiday breaks? If not, I can help there if needed as well!
