### ISSUE TITLE
dynamic updates to 'map_excluded_regions'

### ISSUE THREAD

**Issue by maartenbrinkerink** [Electricity-Transmission-Database/electricity-transmission-database#5]
Just wondering if its possible to let the 'map_excluded_regions' be dynamically updated based on the entries that are in 'nodes.csv'? E.g. Cuba is not in the transmission database but is marked as included, whereas Belize is in the transmission database but is marked as excluded. If we start adding more countries/regions in the transmission database it would be helpful if this is connected to 1 csv that needs to be updated rather than multiple files. @amanmajid

**Comment by amanmajid** [comment]
Hi @maartenbrinkerink 

I've just [refactored](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/commit/51fe41e2b42df176d6fca7d146c05bf68ef095c8) the `map_excluded_regions` function to plot only those countries that are identified in the transmission database. The errors before were because I was incorrectly plotting the nodes in OSeMOSYS-Global, rather than our database coverage. The [updated figure](https://github.com/Electricity-Transmission-Database/electricity-transmission-database/blob/main/outputs/figures/map_excluded_regions.png) is also in the repo.
